name: e2e-checks

on:
  pull_request:
    branches:
      - dev
  push:
    branches:
      - dev

jobs:

  e2e-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        k8s-version:
          - v1.22
          - v1.21
          - v1.20
          - v1.19
        include:
          - k8s-version: v1.22
            kind-node-image: kindest/node:v1.22.0@sha256:b8bda84bb3a190e6e028b1760d277454a72267a5454b57db34437c34a588d047
          - k8s-version: v1.21
            kind-node-image: kindest/node:v1.21.1@sha256:69860bda5563ac81e3c0057d654b5253219618a22ec3a346306239bba8cfa1a6
          - k8s-version: v1.20
            kind-node-image: kindest/node:v1.20.2@sha256:8f7ea6e7642c0da54f04a7ee10431549c0257315b3a634f6ef2fecaaedb19bab
          - k8s-version: v1.19
            kind-node-image: kindest/node:v1.19.7@sha256:a70639454e97a4b733f9d9b67e12c01f6b0297449d5b9cbbef87473458e26dca

    name: e2e-tests for K8s ${{ matrix.k8s-version }}

    steps:

    - name: Check out the repo
      uses: actions/checkout@v2

  # Collect Release SHA Tag is used to to collect information needed later in the action and expose it so it can be referenced
    - name: Collect Release SHA Tag
      id: prep
      run: |
        echo ::set-output name=releasetag::sha-${GITHUB_SHA::7}

    # Part of docker/build-push-action@v2; setting up the build system
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      with:
        driver: docker-container
        driver-opts: image=moby/buildkit:buildx-stable-1
        use: true

    - name: Build imageswap-init Container Image
      timeout-minutes: 10
      uses: docker/build-push-action@v2
      with:
        context: ./app/imageswap-init/
        # file should be specified relative to the repo root rather than relative to the context
        file: ./app/imageswap-init/Dockerfile
        # Don't push the image to a registry
        push: false
        # Load image into local docker default context
        outputs: type=docker
        # Uses the releasetag output exposed by the Collect Release SHA Tag step to set the tag under v2
        tags: thewebroot/imageswap-init:${{ steps.prep.outputs.releasetag }}


    - name: Build imageswap Container Image
      timeout-minutes: 10
      uses: docker/build-push-action@v2
      with:
        context: ./app/imageswap/
        # file should be specified relative to the repo root rather than relative to the context
        file: ./app/imageswap/Dockerfile
        # Don't push the image to a registry
        push: false
        # Load image into local docker default context
        outputs: type=docker
        # Uses the releasetag output exposed by the Collect Release SHA Tag step to set the tag under v2
        tags: thewebroot/imageswap:${{ steps.prep.outputs.releasetag }}

    - name: Setup KinD Cluster
      timeout-minutes: 10
      uses: engineerd/setup-kind@v0.5.0
      with:
          version: "v0.11.1"
          image: ${{ matrix.kind-node-image }}
          wait: 360s

    - name: Install ImageSwap
      timeout-minutes: 10
      run: |
        echo "Loading ImageSwap images to KinD nodes"
        GIT_SHA=${{github.sha}}
        kind load docker-image thewebroot/imageswap-init:sha-${GIT_SHA::7}
        kind load docker-image thewebroot/imageswap:sha-${GIT_SHA::7}
        echo "Updating target image to use local ref"
        sed -i='' -E "s/(IMAGESWAP_VERSION := )(.*$)/\1sha-${GIT_SHA::7}/" Makefile
        sed -i='' -E "s/(IMAGESWAP_INIT_VERSION := )(.*$)/\1sha-${GIT_SHA::7}/" Makefile
        sed -i='' -E 's/(imagePullPolicy:) Always/\1 IfNotPresent/' deploy/manifests/imageswap-deploy.yaml
        make set-release-version
        make build-single-manifest
        echo "Install ImageSwap"
        make install
        kubectl wait --for=condition=Ready pods -l app=imageswap -n imageswap-system

    - name: Configure Test Namespace
      timeout-minutes: 5
      run: |
        make ns-create-test

    - name: Install Tools
      timeout-minutes: 5
      run: |
        sudo add-apt-repository ppa:rmescandon/yq
        sudo apt update
        sudo apt install yq -y

    - name: Execute Functional Tests
      timeout-minutes: 5
      run: |
        make test-functional
